apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: edu-meet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      -  name: frontend
         image: tejaroyal/edufrontend-app:latest
         ports:
         - containerPort: 80